"""
seed.py — Populate MongoDB with demo equipment, worker, fertilizer, and transport data for KrishiYantra.
Run once: python seed.py
"""

from pymongo import MongoClient
from werkzeug.security import generate_password_hash
import datetime
import os
from dotenv import load_dotenv

load_dotenv()

MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017/krishiyantra")
client = MongoClient(MONGO_URI)
db = client.krishiyantra

# ---- Clear existing demo data ----
print("Clearing existing data...")
for collection in [
    "users",
    "equipment",
    "rentals",
    "kamgar_profiles",
    "kamgar_jobs",
    "fertilizer_products",
    "fertilizer_orders",
    "transport_vehicles",
    "transport_rentals",
]:
    db[collection].delete_many({})

# ---- Seed Users ----
print("Seeding users...")
users = [
    {
        "name": "Vivek Jadhav",
        "email": "rajesh@demo.com",
        "phone": "9699391891",
        "location": "Pune, Maharashtra",
        "password": generate_password_hash("password123"),
        "role": "owner",
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Yash Jadhav",
        "email": "yash@demo.com",
        "phone": "9876543211",
        "location": "Nashik, Maharashtra",
        "password": generate_password_hash("password123"),
        "role": "owner",
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Meena Jadhav",
        "email": "meena@demo.com",
        "phone": "9876543212",
        "location": "Nashik, Maharashtra",
        "password": generate_password_hash("password123"),
        "role": "renter",
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Ramesh Patil",
        "email": "ramesh.kamgar@demo.com",
        "phone": "9823456781",
        "location": "Sangli, Maharashtra",
        "password": generate_password_hash("password123"),
        "role": "kamgar",
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Shankar More",
        "email": "shankar.kamgar@demo.com",
        "phone": "9823456782",
        "location": "Kolhapur, Maharashtra",
        "password": generate_password_hash("password123"),
        "role": "kamgar",
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Anita Salve",
        "email": "anita.kamgar@demo.com",
        "phone": "9823456783",
        "location": "Nanded, Maharashtra",
        "password": generate_password_hash("password123"),
        "role": "kamgar",
        "created_at": datetime.datetime.utcnow()
    }
]
user_ids = db.users.insert_many(users).inserted_ids
print(f"  Inserted {len(user_ids)} users")

owner1_id = user_ids[0]
owner2_id = user_ids[1]
renter_id = user_ids[2]
worker1_id = user_ids[3]
worker2_id = user_ids[4]
worker3_id = user_ids[5]

# ---- Seed Equipment ----
print("Seeding equipment...")
equipment_list = [
    {
        "name": "Mahindra 575 DI Tractor",
        "category": "tractor",
        "price_per_day": 2500,
        "location": "Kolhapur, Maharashtra",
        "description": "Well-maintained Mahindra 575 DI, 47HP. Ideal for field prep, sowing, and transport. Rotavator attachment available.",
        "brand": "Mahindra",
        "year": 2020,
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "John Deere 5310 Tractor",
        "category": "tractor",
        "price_per_day": 3200,
        "location": "Kolhapur, Maharashtra",
        "description": "Powerful John Deere 5310, 55HP. Perfect for heavy field operations and transportation.",
        "brand": "John Deere",
        "year": 2021,
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Combine Harvester (Self-Propelled)",
        "category": "harvester",
        "price_per_day": 5500,
        "location": "Kolhapur, Maharashtra",
        "description": "Self-propelled combine harvester for wheat and paddy. Minimal crop loss, very efficient.",
        "brand": "CLAAS",
        "year": 2019,
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Rotavator 7 ft",
        "category": "rotavator",
        "price_per_day": 1200,
        "location": "Kolhapur, Maharashtra",
        "description": "Heavy duty 7ft rotavator. Prepares seedbed with excellent soil tilth for all crops.",
        "brand": "Shaktiman",
        "year": 2022,
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Power Sprayer 16L",
        "category": "sprayer",
        "price_per_day": 600,
        "location": "Kolhapur, Maharashtra",
        "description": "Battery-powered knapsack sprayer, 16L capacity. Ideal for pesticide and fertilizer application.",
        "brand": "Neptune",
        "year": 2023,
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Paddy Thresher",
        "category": "thresher",
        "price_per_day": 1400,
        "location": "Kolhapur, Maharashtra",
        "description": "Efficient paddy thresher. Separates grain quickly with low breakage. Diesel powered.",
        "brand": "Agrimaster",
        "year": 2021,
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "MB Plough 3 Furrow",
        "category": "plough",
        "price_per_day": 900,
        "location": "Sangli, Maharashtra",
        "description": "3-furrow MB plough for deep primary tillage. Suitable for heavy clay soils.",
        "brand": "Fieldking",
        "year": 2020,
        "owner_name": "Yash Jadhav",
        "owner_phone": "9876543211",
        "owner_id": owner2_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Seed Drill 9-Row",
        "category": "seeder",
        "price_per_day": 1100,
        "location": "Sangli, Maharashtra",
        "description": "9-row seed drill for precise sowing of soybean, wheat, gram. Uniform row spacing.",
        "brand": "Agro Master",
        "year": 2022,
        "owner_name": "Yash Jadhav",
        "owner_phone": "9876543211",
        "owner_id": owner2_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Diesel Water Pump 5HP",
        "category": "pump",
        "price_per_day": 550,
        "location": "Sangli, Maharashtra",
        "description": "5HP diesel water pump. High discharge rate for field irrigation. Easy to transport.",
        "brand": "Kirloskar",
        "year": 2021,
        "owner_name": "Yash Jadhav",
        "owner_phone": "9876543211",
        "owner_id": owner2_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Mini Power Tiller",
        "category": "tractor",
        "price_per_day": 1600,
        "location": "Sangli, Maharashtra",
        "description": "Versatile mini power tiller for small farms and hilly terrain. 7HP, lightweight.",
        "brand": "VST Shakti",
        "year": 2022,
        "owner_name": "Yash Jadhav",
        "owner_phone": "9876543211",
        "owner_id": owner2_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "Laser Land Leveler",
        "category": "tractor",
        "price_per_day": 3800,
        "location": "Sangli, Maharashtra",
        "description": "GPS-guided laser land leveler. Levels fields accurately for water-efficient irrigation.",
        "brand": "Trimble",
        "year": 2020,
        "owner_name": "Yash Jadhav",
        "owner_phone": "9876543211",
        "owner_id": owner2_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
    {
        "name": "John Deere Combine Harvester W70",
        "category": "harvester",
        "price_per_day": 4800,
        "location": "Sangli, Maharashtra",
        "description": "John Deere W70 combine for wheat, soybean, and sunflower. Excellent threshing quality.",
        "brand": "John Deere",
        "year": 2021,
        "owner_name": "Yash Jadhav",
        "owner_phone": "9876543211",
        "owner_id": owner2_id,
        "available": True,
        "created_at": datetime.datetime.utcnow()
    },
]

eq_ids = db.equipment.insert_many(equipment_list).inserted_ids
print(f"  Inserted {len(eq_ids)} equipment records")

# ---- Seed Worker Profiles ----
print("Seeding worker profiles...")
worker_profiles = [
    {
        "user_id": worker1_id,
        "name": "Ramesh Patil",
        "phone": "9823456781",
        "location": "Sangli, Maharashtra",
        "skills": ["field_work", "sowing", "harvesting", "tractor_operation"],
        "experience_years": 7,
        "availability": "Available for next 3 days",
        "hourly_rate": 260,
        "daily_rate": 2200,
        "description": "Experienced farm labourer specializing in sowing, transplanting, and combine support operations.",
        "photo_url": "",
        "available": True,
        "status": "active",
        "rating_avg": 4.7,
        "rating_count": 18,
        "created_at": datetime.datetime.utcnow(),
        "updated_at": datetime.datetime.utcnow(),
    },
    {
        "user_id": worker2_id,
        "name": "Shankar More",
        "phone": "9823456782",
        "location": "Kolhapur, Maharashtra",
        "skills": ["spraying", "weeding", "crop_monitoring", "manual_labour"],
        "experience_years": 5,
        "availability": "Available immediately",
        "hourly_rate": 220,
        "daily_rate": 1800,
        "description": "Skilled in crop care, spraying, inter-cultivation, and seasonal farm maintenance work.",
        "photo_url": "",
        "available": True,
        "status": "active",
        "rating_avg": 4.5,
        "rating_count": 12,
        "created_at": datetime.datetime.utcnow(),
        "updated_at": datetime.datetime.utcnow(),
    },
    {
        "user_id": worker3_id,
        "name": "Anita Salve",
        "phone": "9823456783",
        "location": "Nanded, Maharashtra",
        "skills": ["harvesting", "sorting", "field_support", "grading"],
        "experience_years": 4,
        "availability": "Available after 2 days",
        "hourly_rate": 240,
        "daily_rate": 1900,
        "description": "Reliable farm support professional focused on harvesting, sorting, and field logistics.",
        "photo_url": "",
        "available": False,
        "status": "active",
        "rating_avg": 4.6,
        "rating_count": 9,
        "created_at": datetime.datetime.utcnow(),
        "updated_at": datetime.datetime.utcnow(),
    }
]
db.kamgar_profiles.insert_many(worker_profiles)
print(f"  Inserted {len(worker_profiles)} worker profiles")

# ---- Seed Worker Jobs ----
print("Seeding worker bookings...")
worker_profile_ids = list(db.kamgar_profiles.find({"user_id": {"$in": [worker1_id, worker2_id, worker3_id]}}))
worker_one_id = worker_profile_ids[0]["_id"] if worker_profile_ids else None

if worker_one_id:
    db.kamgar_jobs.insert_one({
        "worker_id": worker_one_id,
        "farmer_id": renter_id,
        "farmer_name": "Meena Jadhav",
        "worker_name": "Ramesh Patil",
        "location": "Miraj, Maharashtra",
        "job_type": "field_work",
        "title": "Sugarcane field maintenance",
        "description": "Need 2 workers for weed removal and bund maintenance for 2 days.",
        "start_date": "2026-09-03",
        "end_date": "2026-09-04",
        "work_hours": "8 hours/day",
        "estimated_cost": 4400,
        "payment_status": "pending",
        "status": "requested",
        "created_at": datetime.datetime.utcnow(),
        "updated_at": datetime.datetime.utcnow(),
    })
    print("  Inserted 1 sample worker booking")

# ---- Seed Fertilizer Products ----
print("Seeding fertilizer products...")
fertilizer_products = [
    {
        "name": "Urea 46% N",
        "category": "nitrogen",
        "brand": "IFFCO",
        "variant": "50kg bag",
        "price_per_bag": 280,
        "stock_available": 120,
        "location": "Nashik, Maharashtra",
        "supplier_name": "Yash Jadhav",
        "supplier_phone": "9876543211",
        "supplier_id": owner2_id,
        "description": "High purity nitrogen fertilizer for paddy, wheat, and sugarcane crop growth.",
        "rating_avg": 4.7,
        "rating_count": 23,
        "created_at": datetime.datetime.utcnow(),
        "updated_at": datetime.datetime.utcnow(),
    },
    {
        "name": "DAP (18:46:0)",
        "category": "phosphorus",
        "brand": "Coromandel",
        "variant": "50kg bag",
        "price_per_bag": 1350,
        "stock_available": 75,
        "location": "Pune, Maharashtra",
        "supplier_name": "Vivek Jadhav",
        "supplier_phone": "9699391891",
        "supplier_id": owner1_id,
        "description": "Balanced phosphorus-rich fertilizer for root development and early plant vigor.",
        "rating_avg": 4.8,
        "rating_count": 30,
        "created_at": datetime.datetime.utcnow(),
        "updated_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Complex Fertilizer 20:20:20",
        "category": "balanced",
        "brand": "Nutrient Plus",
        "variant": "50kg bag",
        "price_per_bag": 980,
        "stock_available": 95,
        "location": "Sangli, Maharashtra",
        "supplier_name": "Yash Jadhav",
        "supplier_phone": "9876543211",
        "supplier_id": owner2_id,
        "description": "All-purpose NPK mix for vegetables, cotton, and cereal crops in nutrient-deficient soil.",
        "rating_avg": 4.6,
        "rating_count": 20,
        "created_at": datetime.datetime.utcnow(),
        "updated_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Potash MOP",
        "category": "potash",
        "brand": "Krishak Bharti",
        "variant": "50kg bag",
        "price_per_bag": 840,
        "stock_available": 80,
        "location": "Kolhapur, Maharashtra",
        "supplier_name": "Vivek Jadhav",
        "supplier_phone": "9699391891",
        "supplier_id": owner1_id,
        "description": "Potassium-rich fertilizer to increase crop resilience, fruit quality, and stress tolerance.",
        "rating_avg": 4.5,
        "rating_count": 16,
        "created_at": datetime.datetime.utcnow(),
        "updated_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Bio Organic Compost",
        "category": "organic",
        "brand": "GreenGold",
        "variant": "25kg bag",
        "price_per_bag": 430,
        "stock_available": 110,
        "location": "Nanded, Maharashtra",
        "supplier_name": "Vivek Jadhav",
        "supplier_phone": "9699391891",
        "supplier_id": owner1_id,
        "description": "Organic nutrient source for soil health improvement and long-term fertility building.",
        "rating_avg": 4.7,
        "rating_count": 18,
        "created_at": datetime.datetime.utcnow(),
        "updated_at": datetime.datetime.utcnow(),
    }
]
product_ids = db.fertilizer_products.insert_many(fertilizer_products).inserted_ids
print(f"  Inserted {len(product_ids)} fertilizer products")

# ---- Seed Sample Fertilizer Order ----
print("Seeding sample fertilizer order...")
db.fertilizer_orders.insert_one({
    "product_id": product_ids[0],
    "product_name": "Urea 46% N",
    "farmer_id": renter_id,
    "farmer_name": "Meena Jadhav",
    "supplier_id": owner2_id,
    "supplier_name": "Yash Jadhav",
    "quantity": 4,
    "unit_price": 280,
    "total_amount": 1120,
    "delivery_location": "Nashik, Maharashtra",
    "delivery_date": "2026-09-07",
    "payment_status": "pending",
    "status": "requested",
    "created_at": datetime.datetime.utcnow(),
    "updated_at": datetime.datetime.utcnow(),
})
print("  Inserted 1 sample fertilizer order")

# ---- Seed Transport Vehicles ----
print("Seeding transport vehicles...")
transport_vehicles = [
    {
        "name": "Tata Ace Gold (Chota Hathi)",
        "vehicle_type": "small_truck",
        "capacity": "1 Ton",
        "price_per_day": 1800,
        "location": "Pune, Maharashtra",
        "city": "Pune",
        "district": "Pune",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "description": "Tata Ace Gold 'Chota Hathi' small farm truck. Perfect for carrying vegetable crates, fruit baskets, and fertilizer bags directly from farm to local APMC mandi.",
        "image_url": "/images/transport/tata_ace.jpg",
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "owner_id_str": str(owner1_id),
        "rating_avg": 4.8,
        "rating_count": 28,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Mahindra Bolero Pickup Extra Long",
        "vehicle_type": "pickup",
        "capacity": "1.7 Ton",
        "price_per_day": 2400,
        "location": "Kolhapur, Maharashtra",
        "city": "Kolhapur",
        "district": "Kolhapur",
        "latitude": 16.7050,
        "longitude": 74.2433,
        "description": "Mahindra Bolero Pickup with extra-long body and heavy-duty leaf springs. Specially suited for sugarcane stalks, jaggery blocks, and vegetable crate transport.",
        "image_url": "/images/transport/bolero_pickup.jpg",
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "owner_id_str": str(owner1_id),
        "rating_avg": 4.7,
        "rating_count": 24,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Mahindra Tractor with Hydraulic Trolley",
        "vehicle_type": "tractor_trolley",
        "capacity": "8 Ton",
        "price_per_day": 2200,
        "location": "Ahmednagar, Maharashtra",
        "city": "Ahmednagar",
        "district": "Ahmednagar",
        "latitude": 19.0952,
        "longitude": 74.7496,
        "description": "Heavy-duty farm tractor with hydraulic tipping trolley. Ideal for bulk sugarcane haulage from farm field directly to sugar factory, grain transport, and manure distribution.",
        "image_url": "/images/transport/tractor_trolley_red.jpg",
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "owner_id_str": str(owner1_id),
        "rating_avg": 4.9,
        "rating_count": 36,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Tata 407 Gold SFC Agricultural Truck",
        "vehicle_type": "big_truck",
        "capacity": "4 Ton",
        "price_per_day": 3800,
        "location": "Nashik, Maharashtra",
        "city": "Nashik",
        "district": "Nashik",
        "latitude": 19.9975,
        "longitude": 73.7898,
        "description": "Tata 407 Gold SFC commercial truck with high-side agricultural body. Best for onion sacks, grape crates, and grain bags delivery to major wholesale markets.",
        "image_url": "/images/transport/tata_407.jpg",
        "owner_name": "Yash Jadhav",
        "owner_phone": "9876543211",
        "owner_id": owner2_id,
        "owner_id_str": str(owner2_id),
        "rating_avg": 4.6,
        "rating_count": 21,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Ashok Leyland Dost Strong Small Truck",
        "vehicle_type": "small_truck",
        "capacity": "1.5 Ton",
        "price_per_day": 2100,
        "location": "Sangli, Maharashtra",
        "city": "Sangli",
        "district": "Sangli",
        "latitude": 16.8524,
        "longitude": 74.5815,
        "description": "Ashok Leyland Dost Strong small cargo truck. Reliable diesel engine with flatbed body, ideal for fresh tomatoes, green chilies, turmeric sacks, and milk can transit.",
        "image_url": "/images/transport/leyland_dost.jpg",
        "owner_name": "Yash Jadhav",
        "owner_phone": "9876543211",
        "owner_id": owner2_id,
        "owner_id_str": str(owner2_id),
        "rating_avg": 4.7,
        "rating_count": 19,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Mahindra 275 DI Tractor with Grain Trolley",
        "vehicle_type": "tractor_trolley",
        "capacity": "5 Ton",
        "price_per_day": 1700,
        "location": "Satara, Maharashtra",
        "city": "Satara",
        "district": "Satara",
        "latitude": 17.6805,
        "longitude": 74.0183,
        "description": "Blue Mahindra 275 DI tractor hitched with a 5-ton metal farm trolley. Excellent for wheat, soybean, and paddy harvest hauling across rough mud and field roads.",
        "image_url": "/images/transport/tractor_trolley_blue.jpg",
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "owner_id_str": str(owner1_id),
        "rating_avg": 4.8,
        "rating_count": 25,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Mahindra Bolero Camper 4x4 Farm Pickup",
        "vehicle_type": "pickup",
        "capacity": "1.2 Ton",
        "price_per_day": 2500,
        "location": "Solapur, Maharashtra",
        "city": "Solapur",
        "district": "Solapur",
        "latitude": 17.6599,
        "longitude": 75.9064,
        "description": "4x4 Mahindra Bolero pickup truck built for wet farm roads and monsoon crop harvesting. Carries pomegranate crates, cotton bags, and farm workers safely.",
        "image_url": "/images/transport/bolero_pickup.jpg",
        "owner_name": "Yash Jadhav",
        "owner_phone": "9876543211",
        "owner_id": owner2_id,
        "owner_id_str": str(owner2_id),
        "rating_avg": 4.6,
        "rating_count": 17,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Eicher Pro 2049 Big Cargo Truck",
        "vehicle_type": "big_truck",
        "capacity": "7 Ton",
        "price_per_day": 5200,
        "location": "Aurangabad, Maharashtra",
        "city": "Aurangabad",
        "district": "Aurangabad",
        "latitude": 19.8762,
        "longitude": 75.3433,
        "description": "Eicher Pro heavy cargo truck for large-scale agricultural transport. Perfect for bulk cotton bales, corn loads, and seasonal harvest shipments between districts.",
        "image_url": "/images/transport/tata_407.jpg",
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "owner_id_str": str(owner1_id),
        "rating_avg": 4.8,
        "rating_count": 31,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Tata Yodha 4x4 Farm Pickup",
        "vehicle_type": "pickup",
        "capacity": "1.7 Ton",
        "price_per_day": 2600,
        "location": "Latur, Maharashtra",
        "city": "Latur",
        "district": "Latur",
        "latitude": 18.4088,
        "longitude": 76.5604,
        "description": "Rugged Tata Yodha pickup with wide cargo deck and high ground clearance. Tailored for soybean, pulses, and fertilizer bag transportation directly to the farm gate.",
        "image_url": "/images/transport/bolero_pickup.jpg",
        "owner_name": "Yash Jadhav",
        "owner_phone": "9876543211",
        "owner_id": owner2_id,
        "owner_id_str": str(owner2_id),
        "rating_avg": 4.5,
        "rating_count": 14,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Swaraj 744 FE with Heavy Farm Trolley",
        "vehicle_type": "tractor_trolley",
        "capacity": "7 Ton",
        "price_per_day": 2000,
        "location": "Kolhapur, Maharashtra",
        "city": "Kolhapur",
        "district": "Kolhapur",
        "latitude": 16.7050,
        "longitude": 74.2433,
        "description": "High-torque Swaraj tractor equipped with all-steel heavy-duty farm trolley. Ideal for carrying harvested sugarcane directly out of muddy fields during crushing season.",
        "image_url": "/images/transport/tractor_trolley_red.jpg",
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "owner_id_str": str(owner1_id),
        "rating_avg": 4.9,
        "rating_count": 42,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
    {
        "name": "Tata Intra V30 Small Farm Truck",
        "vehicle_type": "small_truck",
        "capacity": "1.3 Ton",
        "price_per_day": 1900,
        "location": "Jalgaon, Maharashtra",
        "city": "Jalgaon",
        "district": "Jalgaon",
        "latitude": 21.0077,
        "longitude": 75.5626,
        "description": "Tata Intra V30 smart compact truck for banana crates, sweet lime boxes, and vegetable dispatch. Power steering and smooth ride protect delicate perishable produce.",
        "image_url": "/images/transport/tata_ace.jpg",
        "owner_name": "Vivek Jadhav",
        "owner_phone": "9699391891",
        "owner_id": owner1_id,
        "owner_id_str": str(owner1_id),
        "rating_avg": 4.6,
        "rating_count": 18,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
    {
        "name": "BharatBenz 1217C Heavy Farm Goods Truck",
        "vehicle_type": "big_truck",
        "capacity": "10 Ton",
        "price_per_day": 6200,
        "location": "Pune, Maharashtra",
        "city": "Pune",
        "district": "Pune",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "description": "10-ton multi-axle agricultural goods truck with high tarpaulin cover. Suited for long-distance transport of grains, sugar bags, and wholesale produce to Vashi/Pune mandis.",
        "image_url": "/images/transport/tata_407.jpg",
        "owner_name": "Yash Jadhav",
        "owner_phone": "9876543211",
        "owner_id": owner2_id,
        "owner_id_str": str(owner2_id),
        "rating_avg": 4.7,
        "rating_count": 29,
        "available": True,
        "created_at": datetime.datetime.utcnow(),
    },
]
transport_ids = db.transport_vehicles.insert_many(transport_vehicles).inserted_ids
print(f"  Inserted {len(transport_ids)} transport vehicles")

print("\n[OK] Seeding complete!")
print("\nDemo Login Credentials:")
print("  Email: rajesh@demo.com  | Password: password123  (Owner)")
print("  Email: meena@demo.com   | Password: password123  (Renter)")
print("  Email: ramesh.kamgar@demo.com | Password: password123  (Kamgar)")
print("  Email: meena@demo.com   | Password: password123  (Renter)")

